{{- if and .Values.enabled (eq (include "gitlab.ingress.enabled" $) "true") (eq (include "gitlab.smartcard.enabled" .) "true") -}}
{{- $appName := "nginx-smartcard" -}}
{{- $componentName := printf "%s-smartcard-ingress-nginx" (include "fullname" .) -}}
{{- $componentClass := "controller" -}}
apiVersion: apps/v1
kind: Service
apiVersion: v1
metadata:
  name: {{ $componentName | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    component: {{ $componentClass }}
spec:
  type: LoadBalancer
  selector:
    app: {{ $appName }}
    component: {{ $componentClass }}
    release: {{ .Release.Name }}
  ports:
    - name: https
      port: {{ template "gitlab.smartcard.port" . }}
      protocol: TCP
      targetPort: https
{{- end -}}
