{{- if and .Values.global.operator.enabled .Values.install.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-crd-installer
  labels:
{{ include "gitlab.standardLabels" $ | indent 4 }}
  annotations:
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
{{ include "gitlab.standardLabels" $ | indent 8 }}        
    spec:
      serviceAccount: {{ template "fullname" . }}-crd-installer
      restartPolicy: Never
{{- include "pullsecrets" $.Values.image | indent 6}}
      containers:
      - name: hyperkube
        image: "{{ .Values.install.image.repository }}:{{ .Values.install.image.tag }}"
        {{ template "gitlab.imagePullPolicy" . }}
        command:
        - ./kubectl
        - apply
        - -f
        - /crd/crd.yaml
        volumeMounts:
        - name: crd
          mountPath: /crd
      volumes:
      - name: crd
        configMap:
          name: {{ template "fullname" . }}-crd-installer
{{- end }}
