{{- if and .Values.global.operator.enabled .Values.install.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-crd-installer
  labels:
{{ include "gitlab.standardLabels" $ | indent 4 }}
  annotations:
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
data:
  crd.yaml: |
    apiVersion: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    metadata:
      creationTimestamp: null
      labels:
        controller-tools.k8s.io: "1.0"
      name: gitlabs.gitlab.com
    spec:
      group: gitlab.com
      names:
        kind: GitLab
        plural: gitlabs
      scope: Namespaced
      validation:
        openAPIV3Schema:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                helmRelease:
                  type: string
                templates:
                  type: object
                  properties:
                    sharedSecretsTemplate:
                      type: object
                      properties:
                        configMapName:
                          type: string
                        configMapKey:
                          type: string
                        roleKey:
                          type: string
                        roleBindingKey:
                          type: string
                        serviceAccountKey:
                          type: string
                      required:
                        - configMapKey
                        - configMapName
                        - roleKey
                        - roleKey
                        - serviceAccountKey
                    migrationsTemplate:
                      type: object
                      properties:
                        configMapName:
                          type: string
                        configMapKey:
                          type: string
                      required:
                        - configMapName
                        - configMapKey
                  required:
                    - migrationsTemplate
                    - sharedSecretsTemplate
                version:
                  type: string
              required:
              - version
              - templates
              - helmRelease
              type: object
            status:
              type: object
      version: v1beta1
    status:
      acceptedNames:
        kind: ""
        plural: ""
      conditions: null
    ---
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: {{ template "fullname" . }}
      labels:
{{ include "gitlab.standardLabels" $ | indent 8 }}
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      creationTimestamp: null
      name: {{ template "fullname" . }}
      labels:
{{ include "gitlab.standardLabels" $ | indent 8 }}
    rules:
    - apiGroups:
      - apps
      resources:
      - deployments
      - statefulsets
      - daemonsets
      verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    - apiGroups:
      - rbac.authorization.k8s.io
      resources:
        - clusterroles
        - clusterrolebindings
        - roles
        - rolebindings
      verbs:
        - get
        - list
        - create
        - update
        - watch
        - patch
        - delete
    - apiGroups:
      - ""
      resources:
      - pods
      - configmaps
      - serviceaccounts
      - secrets
      verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    - apiGroups:
      - batch
      resources:
      - jobs
      verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    - apiGroups:
      - gitlab.com
      resources:
      - gitlabs
      verbs:
      - "*"
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      creationTimestamp: null
      name: {{ template "fullname" . }}
      labels:
{{ include "gitlab.standardLabels" $ | indent 8 }}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: {{ template "fullname" . }}
    subjects:
    - kind: ServiceAccount
      name: {{ template "fullname" . }}
      namespace: {{ .Release.Namespace | quote }}
    ---
    apiVersion: apps/v1beta2
    kind: Deployment
    metadata:
      name: {{ template "fullname" . }}
      labels:
{{ include "gitlab.standardLabels" . | indent 8 }}
    spec:
      replicas: 1
      selector:
        matchLabels:
          component: operator
{{ include "gitlab.standardLabels" . | indent 10 }}
      template:
        metadata:
          labels:
            component: operator
{{ include "gitlab.standardLabels" . | indent 12 }}
        spec:
          serviceAccountName: {{ template "fullname" . }}
          containers:
            - name: {{ .Chart.Name }}
              image: ahmadposten/gitlaboperator
              # image: "{{ .Values.image.repository }}:{{ coalesce .Values.image.tag (include "gitlab.versionTag" . ) }}"
              {{ template "gitlab.imagePullPolicy" . }}
              resources:
{{ toYaml .Values.resources | indent 16 }}
{{- end }}
