{{- if and .Values.global.operator.enabled .Values.install.enabled }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: {{ template "gitlab.operator.crdName" . }}
spec:
  group: {{ template "gitlab.operator.groupName" . }}
  names:
    kind: GitLab
    plural: gitlabs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            helmRelease:
              type: string
            templates:
              type: object
              properties:
                sharedSecretsTemplate:
                  type: object
                  properties:
                    configMapName:
                      type: string
                    configMapKey:
                      type: string
                    roleKey:
                      type: string
                    roleBindingKey:
                      type: string
                    serviceAccountKey:
                      type: string
                  required:
                    - configMapKey
                    - configMapName
                    - roleKey
                    - roleKey
                    - serviceAccountKey
                migrationsTemplate:
                  type: object
                  properties:
                    configMapName:
                      type: string
                    configMapKey:
                      type: string
                  required:
                    - configMapName
                    - configMapKey
              required:
                - migrationsTemplate
                - sharedSecretsTemplate
            version:
              type: string
          required:
          - version
          - templates
          - helmRelease
          type: object
        status:
          type: object
  version: v1beta1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "gitlab.standardLabels" $ | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ template "fullname" . }}
  labels:
{{ include "gitlab.standardLabels" $ | indent 4 }}
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  - daemonsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
    - clusterroles
    - clusterrolebindings
    - roles
    - rolebindings
  verbs:
    - get
    - list
    - create
    - update
    - watch
    - patch
    - delete
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  - serviceaccounts
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - {{ template "gitlab.operator.groupName" . }}
  resources:
  - gitlabs
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: {{ template "fullname" . }}
  labels:
{{ include "gitlab.standardLabels" $ | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "gitlab.standardLabels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: operator
{{ include "gitlab.standardLabels" . | indent 6 }}
  template:
    metadata:
      labels:
        component: operator
{{ include "gitlab.standardLabels" . | indent 8 }}
    spec:
      serviceAccountName: {{ template "fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: ahmadposten/gitlaboperator
          # image: "{{ .Values.image.repository }}:{{ coalesce .Values.image.tag (include "gitlab.versionTag" . ) }}"
          env:
          - name: API_SUBGROUP
            value: {{ .Release.Name }}
          {{ template "gitlab.imagePullPolicy" . }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end }}
