{{- if .Values.global.operator.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-set-gitlab
  labels:
{{ include "gitlab.standardLabels" $ | indent 4 }}
  annotations:
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
{{ include "gitlab.standardLabels" $ | indent 8 }}        
    spec:
      serviceAccount: {{ template "fullname" . }}-set-gitlab
      restartPolicy: Never
{{- include "pullsecrets" $.Values.image | indent 6}}
      containers:
      - name: hyperkube
        image: "{{ .Values.install.image.repository }}:{{ .Values.install.image.tag }}"
        {{ template "gitlab.imagePullPolicy" . }}
        command:
        - ./kubectl
        - apply
        - -f
        - /gitlab/gitlab.yaml
        volumeMounts:
        - name: gitlab
          mountPath: /gitlab
      volumes:
      - name: gitlab
        configMap:
          name: {{ template "fullname" . }}-set-gitlab
{{- end }}
