{{- if .Values.global.operator.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-set-gitlab
  labels:
{{ include "gitlab.standardLabels" $ | indent 4 }}
  annotations:
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-set-gitlab
{{ include "gitlab.standardLabels" $ | indent 8 }}        
    spec:
      serviceAccount: {{ template "fullname" . }}-set-gitlab
      restartPolicy: Never
{{- include "pullsecrets" $.Values.image | indent 6}}
      containers:
      - name: hyperkube
        image: "{{ .Values.install.image.repository }}:{{ .Values.install.image.tag }}"
        {{ template "gitlab.imagePullPolicy" . }}
        command:
        - ./kubectl
        - apply
        - -f
        - /crd/crd.yaml
        volumeMounts:
        - name: crd
          mountPath: /crd
      volumes:
      - name: crd
        configMap:
          name: {{ template "fullname" . }}-set-gitlab
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-set-gitlab
  labels:
{{ include "gitlab.standardLabels" $ | indent 4 }}
  annotations:
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
data:
  crd.yaml: |
    apiVersion: gitlab.com/v1beta1
    kind: GitLab
    metadata:
      labels:
        controller-tools.k8s.io: "1.0"
        revision: "{{ .Release.Revision }}"
{{ include "gitlab.standardLabels" $ | indent 8 }}
      name: {{ template "fullname" . }}
    spec:
      version: {{ .Values.global.gitlabVersion | quote }}
      type: ""
      helmRelease: {{ .Release.Name }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}-set-gitlab
  labels:
    app: {{ template "fullname" . }}-set-gitlab
{{ include "gitlab.standardLabels" $ | indent 4 }}
  annotations:
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "fullname" . }}-set-gitlab
  labels:
{{ include "gitlab.standardLabels" $ | indent 4 }}
  annotations:
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
rules:
- apiGroups:
  - gitlab.com
  resources:
  - gitlabs
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "fullname" . }}-set-gitlab
  labels:
{{ include "gitlab.standardLabels" $ | indent 4 }}
  annotations:
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "fullname" . }}-set-gitlab
subjects:
  - kind: ServiceAccount
    name: {{ template "fullname" . }}-set-gitlab
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
