{{- if .Values.global.operator.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-set-gitlab
  labels:
{{ include "gitlab.standardLabels" $ | indent 4 }}
  annotations:
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
data:
  gitlab.yaml: |
    apiVersion: gitlab.com/v1beta1
    kind: GitLab
    metadata:
      labels:
        controller-tools.k8s.io: "1.0"
        revision: "{{ .Release.Revision }}"
{{ include "gitlab.standardLabels" $ | indent 8 }}
      name: gitlab-{{ .Release.Name }}
    spec:
      version: {{ include "gitlab.operator.gitlabVersion" . | quote }}
      helmRelease: {{ .Release.Name }}
      migrations:
        configMapName: {{ .Values.global.operator.migrations.configMapName }}
        initContainer:
          image: {{ .Values.global.operator.migrations.initContainer.image }}
          tag: {{ .Values.global.operator.migrations.initContainer.tag }}
        image: {{ .Values.global.operator.migrations.image }}
        railsSecret:
          name: {{ template "gitlab.rails-secrets.secret" . }}
          key: secrets.yml
        redisPassword:
          name: {{ template "gitlab.redis.password.secret" . }}
          key: {{ template "gitlab.redis.password.key" . }}
        psqlPassword:
          name: {{ template "gitlab.psql.password.secret" . }}
          key: {{ template "gitlab.psql.password.key" . }}
        initialRootPassword:
          name: {{ template "gitlab.migrations.initialRootPassword.secret" . }}
          key: {{ template "gitlab.migrations.initialRootPassword.key" . }}
        gitLabRunnerRegistationToken:
          name: {{ template "gitlab.gitlab-runner.registrationToken.secret" . }}
          key: runner-registration-token
{{- end }}
