{{- if .Values.global.operator.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-set-gitlab
  labels:
{{ include "gitlab.standardLabels" $ | indent 4 }}
  annotations:
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
data:
  crd.yaml: |
    apiVersion: gitlab.com/v1beta1
    kind: GitLab
    metadata:
      labels:
        controller-tools.k8s.io: "1.0"
        revision: "{{ .Release.Revision }}"
{{ include "gitlab.standardLabels" $ | indent 8 }}
      name: {{ template "fullname" . }}
    spec:
      version: {{ .Values.global.gitlabVersion | quote }}
      type: ""
      helmRelease: {{ .Release.Name }}
{{- end }}
