# Default values for sidekiq.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: 
  pullSecrets: []
  # pullPolicy: IfNotPresent
  # tag: latest

# Install the operator as well
install: true
crd:
  image:
    repository: gcr.io/google_containers/hyperkube
    tag: v1.9.0
    pullSecrets: []
    #pullPolicy: IfNotPresent
