# Default values for sidekiq.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: registry.gitlab.com/gitlab-org/distribution/gitlab-operator
  tag: latest
  pullSecrets: []
  pullPolicy: Always

init:
  resources:
    requests:
      cpu: 50m

install:
  # Install the operator as well
  enabled: true
  image:
    repository: registry.gitlab.com/gitlab-org/build/cng/kubectl
    tag: 1f8690f03f7aeef27e727396927ab3cc96ac89e7
    pullSecrets: []
    #pullPolicy: IfNotPresent

resources:
  # limits:
  #  cpu: 1
  #  memory: 2G
  requests:
    cpu: 100m
    memory: 64M
