{{- if and .Values.enabled (not .Values.global.operator.enabled) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "migrations.jobname" . }}
  labels:
{{ include "gitlab.standardLabels" . | indent 4 }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
{{ include (print $.Template.BasePath "/_podspec.yaml") . | indent 6 }}
{{- end }}
