{{- if and .Values.enabled .Values.rbac.create }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-gitlab-grafana
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "gitlab.standardLabels" . | indent 4 }}
{{- if not .Values.global.operator.enabled }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-8"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
{{- end }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "patch"]
{{- end }}
