{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grafana-generate-secret
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "gitlab.standardLabels" . | indent 4 }}
{{- if not .Values.global.operator.enabled }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-8"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
{{- end }}
data:
  generate-secret.sh: |-
{{ include (print $.Template.BasePath "/_generate-secret.sh") . | indent 4 }}
{{- end }}
