{{- if .Values.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-grafana-initial-password
  namespace: {{ $.Release.Namespace }}
  labels:
    secretType: initial-password
{{ include "gitlab.standardLabels" . | indent 4 }}
data:
  password: {{ "foobar" | b64enc }}
{{- end }}
