## GitLab Grafana configuration
## If enabled, we will deploy a secured Grafana

# This chart is controlled by `global.grafana.enabled`
global: {}

# We supply an Ingress resource that locates Grafana under /-/grafana
# NOTE: these values are placeholders for template functionality.
ingress:
  tls: {}
  annotations: {}

