
enabled: true

ingress:
  tls: {}
  annotations: {}

## Support for tolerations for pod scheduling
tolerations: []

serviceAccount:
  create: true
  name: my-gitlab-grafana  # Specify a pre-existing ServiceAccount name
rbac:
  create: true

resources:
  requests:
    cpu: 50m
securityContext:
  # in debian/alpine based images, this is `nobody:nogroup`
  runAsUser: 65534
  fsGroup: 65534


grafana:
  adminUser: admin
  adminPassword: admin
  ## The following settings allow Grafana to dynamically create
  ## dashboards and datasources from configmaps. See
  ## https://github.com/helm/charts/tree/master/stable/grafana#sidecar-for-dashboards
  sidecar:
    dashboards:
      enabled: true
      label: gitlab_grafana_dashboard
    datasources:
      enabled: true
      label: gitlab_grafana_datasource
  grafana.ini:
    server:
      root_url: http://localhost/-/grafana/
  extraSecretMounts:
    - name: initial-password
      mountPath: /tmp/initial
      readOnly: true
      secretName: gitlab-grafana-initial-password
      defaultMode: 400
  extraConfigmapMounts:
    - name: import-secret
      mountPath: /tmp/scripts
      configMap: gitlab-grafana-import-secret
      readOnly: true
  command: [ "sh", "-x", "/tmp/scripts/import-secret.sh" ]